### ISSUE TITLE
dataset download

### ISSUE THREAD

**Issue by UestcJay** [albertpumarola/D-NeRF#8]
The data download link is invalid from drive, my download failed from dropbox, can you just update the drive link?

**Comment by StarsTesla** [comment]
+1

**Comment by albertpumarola** [comment]
Done

**Comment by l-mengwei** [comment]
> Done

Hello, could you update the datasets download link again? The google drive link is invalid, and the download of dropbox link fails.  Look forward to your reply, thanks ！
